name: Build ZMK Firmware

on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5-branch
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zmk-modules
        with:
          path: |
            zmk/modules/
            zmk/tools/
            zmk/zephyr/
            zmk/bootloader/
            zmk/build/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('zmk/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: West Init
        run: |
          west init -l zmk/app
          west update
          west zephyr-export
      
      - name: Build firmware
        run: |
          west build -p=always -b nice_nano_v2 zmk/app -- \
            -DSHIELD=your_keyboard_name \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: zmk/app/build/zephyr/zmk.uf2
